// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLFNVawrsr7TdwEf7J-e6Sa5kFchlqwdw',
    appId: '1:364084950934:web:9e0bc9b911e4e005b7cfb7',
    messagingSenderId: '364084950934',
    projectId: 'loginscreen-577d8',
    authDomain: 'loginscreen-577d8.firebaseapp.com',
    storageBucket: 'loginscreen-577d8.firebasestorage.app',
    measurementId: 'G-L50NJGGRV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZEpYsNke55QoSWt9uOK7jYIrOcApJh0',
    appId: '1:364084950934:android:acb6e7df4c78d0bab7cfb7',
    messagingSenderId: '364084950934',
    projectId: 'loginscreen-577d8',
    storageBucket: 'loginscreen-577d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpBKZAvVZznsIQNtApB5EztgPpWpmrKuA',
    appId: '1:364084950934:ios:802a44e66c9cfecdb7cfb7',
    messagingSenderId: '364084950934',
    projectId: 'loginscreen-577d8',
    storageBucket: 'loginscreen-577d8.firebasestorage.app',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpBKZAvVZznsIQNtApB5EztgPpWpmrKuA',
    appId: '1:364084950934:ios:802a44e66c9cfecdb7cfb7',
    messagingSenderId: '364084950934',
    projectId: 'loginscreen-577d8',
    storageBucket: 'loginscreen-577d8.firebasestorage.app',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLFNVawrsr7TdwEf7J-e6Sa5kFchlqwdw',
    appId: '1:364084950934:web:b8ac1816d247d249b7cfb7',
    messagingSenderId: '364084950934',
    projectId: 'loginscreen-577d8',
    authDomain: 'loginscreen-577d8.firebaseapp.com',
    storageBucket: 'loginscreen-577d8.firebasestorage.app',
    measurementId: 'G-EB57842VLN',
  );
}
